name: bakliwal_news
description: "A News Applicaiton made with Flutter. Bakliwal News is a user generated news applicaiton with upto date Tech news."

publish_to: "none"

version: 3.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  xml: ^5.0.0
  http: ^1.2.0
  dio: ^5.4.1
  html: ^0.15.4
  intl: ^0.19.0
  get_it: ^7.6.7
  shimmer: ^3.0.0
  provider: ^6.1.1
  share_plus: ^6.3.4
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  profanity_filter: ^2.0.0
  flutter_typeahead: ^5.2.0
  flutter_screenutil: ^5.9.0
  flutter_markdown: ^0.6.20+1
  permission_handler: ^11.3.0
  # !! Due to version dispute
  # flutter_native_splash: 2.3.10
  flutter_feather_icons: ^2.0.0+1

  bloc: ^8.1.3
  flutter_bloc: ^8.1.4

  url_launcher: ^6.2.4

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_database: ^10.4.5

  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#000000"
  image: assets/images/Logos/BakliwalNewsAppLogo.png
  android_12:
    image: assets/images/Logos/BakliwalNewsAppLogo.png
    color: "#000000"
  android: true
  ios: true
  web: true
  image_web: assets/images/Logos/BakliwalNewsAppLogo.png

flutter_launcher_icons:
  image_path_android: "assets/images/Logos/BakliwalNewsAppLogo.jpg"
  image_path_ios: "assets/images/Logos/BakliwalNewsAppLogo.jpg"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin/Cabin-Italic.ttf
          style: italic
        - asset: assets/fonts/Cabin/Cabin-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cabin/Cabin-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Cabin/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin/Cabin-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Cabin/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin/Cabin-MediumItalic.ttf
          weight: 500
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.otf
          weight: 700

    - family: Silkscreen
      fonts:
        - asset: assets/fonts/Silkscreen/Silkscreen-Regular.ttf
        - asset: assets/fonts/Silkscreen/Silkscreen-Bold.ttf
          weight: 700

    - family: CustomeIcons
      fonts:
        - asset: assets/fonts/CustomeIcons.ttf
